Vagrant.configure('2') do |config|
  config.vm.network "public_network", bridge: "wlo1"  #Assign IPs from the subnet of the host machine.
  config.vm.define 'node-a' do |node|
    node.vm.box = 'ubuntu/focal64'
    node.vm.provider 'virtualbox' do |v|
      v.memory = 2048
    end
  end
  config.vm.define 'node-b' do |node|
    node.vm.box = 'ubuntu/focal64'
    node.vm.provider 'virtualbox' do |v|
      v.memory = 2048
    end
  end
end
