Vagrant.configure('2') do |config|
    config.vm.network "public_network", bridge: "wlo1"  #Assign IPs from the subnet of the host machine.
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "../ansible/playbook.yaml"
        ansible.groups = {
            "group1" => ["node-a"],
            "group2" => ["node-b"],
            "all:children" => ["group1", "group2"]
        }
    end
    config.vm.define 'node-a' do |node|
      node.vm.box = 'ubuntu/focal64'
      node.vm.provider 'virtualbox' do |v|
        v.memory = 2048
      end
    end
    config.vm.define 'node-b' do |node|
      node.vm.box = 'ubuntu/focal64'
      node.vm.provider 'virtualbox' do |v|
        v.memory = 2048
      end
    end
  end
